// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLEfQWqGgZoPY75EzsyRXsVJr8i8RGCfE',
    appId: '1:493428856672:web:3d43ebf6ab9eba56bbb005',
    messagingSenderId: '493428856672',
    projectId: 'shop-manager-flutter-ai',
    authDomain: 'shop-manager-flutter-ai.firebaseapp.com',
    storageBucket: 'shop-manager-flutter-ai.firebasestorage.app',
    measurementId: 'G-W2KPRSSCXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4WMML2eNpEfxQl1yv__bNuRI658jzXY',
    appId: '1:493428856672:android:219b706ec2a80311bbb005',
    messagingSenderId: '493428856672',
    projectId: 'shop-manager-flutter-ai',
    storageBucket: 'shop-manager-flutter-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKNmQOFqyRsSE453OCi-xRf79XLnWvvJY',
    appId: '1:493428856672:ios:0db0d2996766c678bbb005',
    messagingSenderId: '493428856672',
    projectId: 'shop-manager-flutter-ai',
    storageBucket: 'shop-manager-flutter-ai.firebasestorage.app',
    iosBundleId: 'biz.sparkify.shopmanager.shopManagerAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKNmQOFqyRsSE453OCi-xRf79XLnWvvJY',
    appId: '1:493428856672:ios:0db0d2996766c678bbb005',
    messagingSenderId: '493428856672',
    projectId: 'shop-manager-flutter-ai',
    storageBucket: 'shop-manager-flutter-ai.firebasestorage.app',
    iosBundleId: 'biz.sparkify.shopmanager.shopManagerAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLEfQWqGgZoPY75EzsyRXsVJr8i8RGCfE',
    appId: '1:493428856672:web:752be8a6623efaa5bbb005',
    messagingSenderId: '493428856672',
    projectId: 'shop-manager-flutter-ai',
    authDomain: 'shop-manager-flutter-ai.firebaseapp.com',
    storageBucket: 'shop-manager-flutter-ai.firebasestorage.app',
    measurementId: 'G-CRVK43FNEB',
  );
}
